version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: clean-api-v2
    ports:
      - 5000:5000

  db:
    image: 'postgres'
    ports: 
    - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'dealershipv3'
    volumes:
      - data:/var/lib/postgresql/data
      


volumes:
 data:
