name: Deploy API

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: herzliyaaa/clean-arch-api:latest
        context: .

    - name: Deploy to Ubuntu server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.SERVER_HOST }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: |
          cd /opt/dev-api/Clean-Architecture-NodeJS-Express
          sudo docker stop clean-api-v2
          sudo docker rm clean-api-v2
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker-compose down
          sudo docker pull herzliyaaa/clean-arch-api:latest
          sudo docker-compose build
          sudo docker-compose up -d
        debug: true
