name: Deploy API

on:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: herzliyaaa/clean-arch-api:latest
        context: .

    - name: Deploy to Ubuntu server
      uses: actions/ssh-action@v0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull herzliyaaa/clean-arch-api:latest
          docker-compose down
          docker-compose up -d
